In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3]) # create Array from a list
print("Array a:", a)

Array a: [1 2 3]


In [11]:
b = np.arange(0,10,3)  # create array with evenly spaced value
print("Array b:", b)   # It displays the values from 0 to 10 skips 2 steps

Array b: [0 3 6 9]


In [12]:
# Create an array with zeros

d = np.zeros((3,4))   # It creates 3 * 4 Array 3 Roows and 4 coloumns with zero value as float.
print ("Array d:\n", d)

Array d:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
d = np.ones((2,3))   # It creates 2 * 3 Array 3 Roows and 4 coloumns  with value 1 in float
print ("Array d:\n", d) 

Array d:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# Create identity Matrix Array 

f = np.eye(3)                 # It creates array in 3*3 the identical value in diagonal shape.
print("Array identity f\n:", f)

Array identity f
: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Array Manuplation Function:

In [49]:
# reshape an array

a1 = np.array ([1,2,3])
reshaped = np.reshape(a1, (3,1))  # here it reshapes the array  in coloumn
print("Reshaped array:", reshaped)

Reshaped array: [[1]
 [2]
 [3]]


# Flattern  an array

In [26]:
f1 = np.array([[1,2],[3,4],[5,6],[7,8],[9, 10]])
flattern = np.ravel(f1)                         # Here it displays the all the vlaue in 1D array.
print("flattern array:",flattern)

flattern array: [ 1  2  3  4  5  6  7  8  9 10]


# Transpose an array

In [30]:
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print("Transposed array:\n" , transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [31]:
# Stack arrays vertically
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2, b2])  # Stack a and b vertically
print("Stacked arrays:\n", stacked) 

Stacked arrays:
 [[1 2]
 [3 4]]


In [33]:
# Stack arrays horizontal
a1 = np.array([2, 1])
b1 = np.array([3, 4])
stacked = np.hstack([a1, b1])  # Stack a and b vertically
print("Stacked arrays:\n", stacked) 

Stacked arrays:
 [2 1 3 4]


# Adding 2 array : It add 3 to each element of array

In [34]:
g = np.array([1, 2, 3, 4])
added = np.add(g, 3)  # Add 2 to each element
print("Added 3 to g:", added)

Added 3 to g: [4 5 6 7]


In [36]:
# Square each element
squared = np.power(g, 3)  # Square each element  
print("Squared g:", squared)

Squared g: [ 1  8 27 64]


In [39]:
# Square root of each element
sqrt_value = np.sqrt(g)  # Square root of each element
print("Square root of g:", sqrt_value)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [42]:
print(a)
print(g)

[1 2 3]
[1 2 3 4]


In [47]:
a3 = np.array([1,2,3])
dot_product = np.dot(a,g)  # Here size is different so we got error. It should be same size of array as [1,2,3] and [1,2,3] but numbers may vary.
print("Dot product of a1 and a:", dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [50]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [51]:
a3 = np.array([1,2,3])
dot_product = np.dot(a , a1)  # It should be same size  of array as [1,2,3] and [1,2,3] but numbers may vary.
print("Dot product of a and a1:", dot_product)

Dot product of a and a1: 14


# Statistical Function:

In [53]:
s = np.array([1,2,3,4])
Mean = np.mean(s)
print("Mean of s:", Mean)

Mean of s: 2.5


In [54]:
# Standatd Deviation of an array:

std_div = np.std(s)
print("Standard diviation of s:", std_div)

Standard diviation of s: 1.118033988749895


In [55]:
s

array([1, 2, 3, 4])

In [56]:
# Minimum element

mini = np.min(s)
print("Minimum value of s:", mini)

Minimum value of s: 1


In [58]:
# Maximum value of the element
maxi = np.max(s)
print("Miximum value of s:", maxi)

Miximum value of s: 4


# random Sampling function

In [60]:
# Random values of 0 to 1

random_val = np.random.rand(4) # Print any 4 random values from 0 to 4 
print("Random value of 4 is:", random_val)

Random value of 4 is: [0.16471238 0.22610468 0.83330919 0.92616491]
