# Numpy (Matrix): Numpy is the library which handle multidimensional array (nd arry)

# n number of rows
# n no of coloumns

# Uses of Numpy :

# 1. Aerithematic operations
# 2. Statistical operation
# 3. Bitwise operation
# 4. Copying & viewing arrays
# 5. Matrix operation
# 6. Linear algebra.

# Numpy Crash course:

In [2]:
import numpy as np

In [6]:
np.__version__

'2.3.5'

In [7]:
import sys 
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

# Creating array

In [9]:
my_list = [0,1,2,3,4,5]

In [10]:
my_list

[0, 1, 2, 3, 4, 5]

In [11]:
type(my_list)

list

# coverting list to array

In [13]:
np.array(my_list)

array([0, 1, 2, 3, 4, 5])

In [ ]:
array([0,1,2,3,4,5])

In [19]:
print(type(my_list))

<class 'list'>


In [22]:
print(type(array))

NameError: name 'array' is not defined

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [29]:
np.arange(10,20,5,1)

TypeError: Cannot interpret '1' as a data type

In [30]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [31]:
np.zeros(3)

array([0., 0., 0.])

In [32]:
np.zeros(3,dtype = int)

array([0, 0, 0])

In [33]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [35]:
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
np.ones(4)

array([1., 1., 1., 1.])

In [37]:
np.two(3)

AttributeError: module 'numpy' has no attribute 'two'

In [38]:
np.random.rand(3)

array([0.61299175, 0.29893667, 0.77491628])

In [39]:
np.random.rand(3,4)

array([[0.02824779, 0.86152724, 0.32102138, 0.15796602],
       [0.24787851, 0.95961023, 0.61060489, 0.57743582],
       [0.20112156, 0.11398643, 0.64909358, 0.15751446]])

In [42]:
np.random.randint(3)

2

In [43]:
np.random.randint(10,20)

12

In [44]:
np.random.randint(1,10,4)

array([6, 5, 6, 6], dtype=int32)

In [60]:
m = np.random.randint(10,40,(10,10))   # 
print(m)

[[17 15 24 10 20 17 10 24 17 15]
 [11 35 22 21 10 10 34 36 35 28]
 [14 18 35 23 12 28 37 23 34 29]
 [23 34 10 17 13 29 26 32 26 14]
 [17 25 11 22 16 29 14 24 32 17]
 [34 11 12 38 30 28 27 21 33 39]
 [14 14 37 30 35 12 27 26 20 14]
 [18 17 24 30 10 26 21 24 13 10]
 [21 25 27 20 14 17 37 21 38 10]
 [36 21 19 30 34 32 36 35 35 25]]


In [68]:
m = np.random.randint(1,10,(4,6))
print(m)

[[9 3 1 4 1 6]
 [3 3 3 5 5 2]
 [4 2 7 6 8 6]
 [7 3 2 1 2 9]]


In [65]:
m[0]

array([8, 2, 6, 4, 6, 6], dtype=int32)

In [74]:
m = np.random.randint(1,10,(4,6))
print(m)

[[7 3 6 4 7 9]
 [4 6 9 4 5 7]
 [7 8 9 4 2 1]
 [9 7 1 6 8 1]]


In [78]:
print(m[-2,-3])

4


In [3]:
np.arange(-20,10) # here it displays from negavitive numbers to positive number i.e. -20 to 9

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [5]:
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.zeros([10,30])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [9]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunnin g (Float output))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [10]:
print(np.zeros(n,dtype=int)) # converting float to int

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [11]:
n 

(6, 7)

In [12]:
n1

(6, 8)

In [13]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
np.ones(3) # it repeats the vlaue(one) 3 times.

array([1., 1., 1.])

In [19]:
np.ones(3, dtype=int) # here it converts float to integer

array([1, 1, 1])

In [20]:
np.Three(3,4)

AttributeError: module 'numpy' has no attribute 'Three'